export const galleryImages = [
    {
        src: "/gallery/1.png",
        alt: "LCLG: Temerario Reveal",
        credit: "Prakshal Jain",
        description: "Lamborghini Temerario Reveal | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/4.jpg",
        alt: "LCLG: Lotus Owners Drive",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lotus Owners Drive | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/5.jpg",
        alt: "LCLG: Temerario Reveal",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lamborghini Temerario Reveal | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/19.png",
        alt: "Lotus Gate Lotus Club | Cars and Coffee",
        credit: "Kyle Snell",
        description: "Lotus Gate Lotus Club | Cars and Coffee",
    },
    {
        src: "/gallery/2.png",
        alt: "Prakshal Jain with Frank Casanova",
        credit: "Prakshal Jain",
        description: "Prakshal Jain (Founder of Chimera) with Frank Casanova (Former Senior Director leading product-marketing efforts for the Vision Pro at Apple)"
    },
    {
        src: "/gallery/3.png",
        alt: "LCLG: Lotus Owners Drive",
        credit: "Prakshal Jain",
        description: "Lotus Owners Drive | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/8.jpg",
        alt: "LCLG: Lotus Owners Drive",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lotus Owners Drive | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/13.jpg",
        alt: "LCLG: Temerario Reveal",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lamborghini Temerario Reveal | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/6.jpg",
        alt: "LCLG: Lotus Owners Drive",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lotus Owners Drive | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/10.jpg",
        alt: "LCLG: Lotus Owners Drive",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lotus Owners Drive | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/15.jpg",
        alt: "LCLG: Temerario Reveal",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lamborghini Temerario Reveal | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/18.png",
        alt: "Lotus Gate Lotus Club | Cars and Coffee",
        credit: "Kyle Snell",
        description: "Lotus Gate Lotus Club | Cars and Coffee",
    },
    {
        src: "/gallery/9.jpg",
        alt: "LCLG: Lotus Owners Drive",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lotus Owners Drive | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/12.jpg",
        alt: "LCLG: Temerario Reveal",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lamborghini Temerario Reveal | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/14.jpg",
        alt: "LCLG: Temerario Reveal",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lamborghini Temerario Reveal | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/16.jpg",
        alt: "LCLG: Temerario Reveal",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lamborghini Temerario Reveal | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/11.jpg",
        alt: "LCLG: Lotus Owners Drive",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lotus Owners Drive | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/17.jpg",
        alt: "LCLG: Temerario Reveal",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lamborghini Temerario Reveal | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/20.png",
        alt: "Golden Gate Lotus Club | Cars and Coffee",
        credit: "Kyle Snell",
        description: "Golden Gate Lotus Club | Cars and Coffee",
    },
]