export const galleryImages = [
    {
        src: "/gallery/1.png",
        alt: "LCLG: Temerario Reveal",
        credit: "Prakshal Jain",
        description: "Lamborghini Temerario Reveal | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/4.jpg",
        alt: "LCLG: Lotus Owners Drive",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lotus Owners Drive | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/5.jpg",
        alt: "LCLG: Temerario Reveal",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lamborghini Temerario Reveal | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/19.png",
        alt: "Lotus Gate Lotus Club | Cars and Coffee",
        credit: "Kyle Snell",
        description: "Lotus Gate Lotus Club | Cars and Coffee",
    },
    {
        src: "/gallery/2.png",
        alt: "Prakshal Jain with Frank Casanova",
        credit: "Prakshal Jain",
        description: "Prakshal Jain (Founder of Chimera) with Frank Casanova (Former Senior Director leading product-marketing efforts for the Vision Pro at Apple)"
    },
    {
        src: "/gallery/3.png",
        alt: "Prakshal Jain showcasing Chimera at F1 Watch Party | Aston Martin Los Gatos",
        credit: "Prakshal Jain",
        description: "Prakshal Jain (Founder of Chimera) showcasing Chimera at F1 Watch Party | Aston Martin Los Gatos"
    },
    {
        src: "/gallery/26.png",
        alt: "Prakshal Jain showcasing Chimera at F1 Watch Party | Aston Martin Los Gatos",
        credit: "Prakshal Jain",
        description: "Prakshal Jain (Founder of Chimera) showcasing Chimera at F1 Watch Party | Aston Martin Los Gatos"
    },
    {
        src: "/gallery/25.png",
        alt: "Prakshal Jain showcasing Chimera at F1 Watch Party | Aston Martin Los Gatos",
        credit: "Prakshal Jain",
        description: "Prakshal Jain (Founder of Chimera) showcasing Chimera at F1 Watch Party | Aston Martin Los Gatos"
    },

    {
        src: "/gallery/8.jpg",
        alt: "LCLG: Lotus Owners Drive",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lotus Owners Drive | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/13.jpg",
        alt: "LCLG: Temerario Reveal",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lamborghini Temerario Reveal | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/24.png",
        alt: "LCLG: Lotus Owners Drive",
        credit: "Prakshal Jain",
        description: "Lotus Owners Drive | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/6.jpg",
        alt: "LCLG: Lotus Owners Drive",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lotus Owners Drive | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/10.jpg",
        alt: "LCLG: Lotus Owners Drive",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lotus Owners Drive | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/27.png",
        alt: "Prakshal Jain showcasing Chimera at F1 Watch Party | Aston Martin Los Gatos",
        credit: "Prakshal Jain",
        description: "Prakshal Jain (Founder of Chimera) showcasing Chimera at F1 Watch Party | Aston Martin Los Gatos"
    },
    {
        src: "/gallery/15.jpg",
        alt: "LCLG: Temerario Reveal",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lamborghini Temerario Reveal | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/18.png",
        alt: "Lotus Gate Lotus Club | Cars and Coffee",
        credit: "Kyle Snell",
        description: "Lotus Gate Lotus Club | Cars and Coffee",
    },
    {
        src: "/gallery/9.jpg",
        alt: "LCLG: Lotus Owners Drive",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lotus Owners Drive | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/12.jpg",
        alt: "LCLG: Temerario Reveal",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lamborghini Temerario Reveal | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/14.jpg",
        alt: "LCLG: Temerario Reveal",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lamborghini Temerario Reveal | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/16.jpg",
        alt: "LCLG: Temerario Reveal",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lamborghini Temerario Reveal | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/11.jpg",
        alt: "LCLG: Lotus Owners Drive",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lotus Owners Drive | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/17.jpg",
        alt: "LCLG: Temerario Reveal",
        credit: "Solaz Productions | Spencer Solaz",
        description: "Lamborghini Temerario Reveal | Luxury Collections Los Gatos",
    },
    {
        src: "/gallery/20.png",
        alt: "Golden Gate Lotus Club | Cars and Coffee",
        credit: "Kyle Snell",
        description: "Golden Gate Lotus Club | Cars and Coffee",
    },
    {
        src: "/gallery/21.jpeg",
        alt: "Lamborghini Beverly Hills",
        credit: "Ray Gaeta",
        description: "Lamborghini Beverly Hills",
    },
    {
        src: "/gallery/22.jpeg",
        alt: "Porsche Beverly Hills",
        credit: "Ray Gaeta",
        description: "Porsche Beverly Hills",
    },
    {
        src: "/gallery/23.jpeg",
        alt: "Ferrari Beverly Hills",
        credit: "Ray Gaeta",
        description: "Ferrari Beverly Hills",
    },
    {
        src: "/gallery/28.png",
        alt: "Viewing configurations in AR",
        credit: "",
        description: "Viewing configurations in AR",
    },
    {
        src: "/gallery/29.png",
        alt: "",
        credit: "",
        description: "",
    },
    {
        src: "/gallery/30.png",
        alt: "",
        credit: "",
        description: "",
    },
    {
        src: "/gallery/31.jpeg",
        alt: "Chimera at Aston Martin Valhalla Launch Event",
        credit: "",
        description: "Chimera at Aston Martin Valhalla Launch Event",
    },
    {
        src: "/gallery/34.jpeg",
        alt: "Chimera being used to configure Lotus Emira",
        credit: "",
        description: "Chimera being used to configure the new Lotus Emira in Redwood City",
    },
    {
        src: "/gallery/36.jpeg",
        alt: "PJ with Roger Pincombe",
        credit: "",
        description: "PJ (Founder, Chimera) with Roger Pincombe, Head of Developer Experience at Mentra, Executive Director of the Great Star Theater at MIT",
    },
    {
        src: "/gallery/40.jpeg",
        alt: "Chimera at Ram's Winery Lamborghini Event",
        credit: "",
        description: "Chimera at Ram's Winery for Lamborghini Urus Performante Showcase",
    },
    {
        src: "/gallery/32.jpeg",
        alt: "Chimera at Aston Martin Valhalla Launch Event",
        credit: "",
        description: "Chimera at Aston Martin Valhalla Launch Event",
    },
    {
        src: "/gallery/35.jpeg",
        alt: "Chimera at Rolls Royce Event",
        credit: "",
        description: "Chimera at Rolls Royce Black Badge Spectre Showcase x Stephen Jewelry event",
    },
    {
        src: "/gallery/38.jpeg",
        alt: "PJ with Founder of Quizlet at HackMIT",
        credit: "",
        description: "PJ (Founder, Chimera) with Andrew Sutherland (Founder of Quizlet) at HackMIT",
    },
    {
        src: "/gallery/42.jpeg",
        alt: "Chimera Activation at Lamborghini Los Gatos",
        credit: "",
        description: "Chimera activation at Lamborghini Los Gatos",
    },
    {
        src: "/gallery/39.jpeg",
        alt: "Chimera being used to configure Lotus Emira",
        credit: "",
        description: "Chimera being used to build a Lotus Emira",
    },
    {
        src: "/gallery/37.jpeg",
        alt: "PJ with CTO of Dropbox",
        credit: "",
        description: "PJ (Founder, Chimera) with Ali Dasdan, CTO of Dropbox",
    },
    {
        src: "/gallery/33.jpeg",
        alt: "Chimera at Aston Martin Valhalla Launch Event",
        credit: "",
        description: "Chimera at Aston Martin Valhalla Launch Event",
    },
    {
        src: "/gallery/41.jpeg",
        alt: "Chimera at Ram's Winery Lamborghini Event",
        credit: "",
        description: "Chimera at Ram's Winery for Lamborghini Urus Performante Showcase",
    },
    {
        src: "/gallery/43.jpeg",
        alt: "Chimera Activation at Lamborghini Los Gatos",
        credit: "",
        description: "Chimera activation at Lamborghini Los Gatos",
    },
]